### PR TITLE
Give https://lgtm.co/ a try

### PR DESCRIPTION
**Pull request by steveoh**
this is also a test.

### CODE REVIEW

**Comment by stdavis** [comment]
I was somewhat disappointed that you didn't include :sheep:-it. ;)

:shipit:

**Comment by steveoh** [comment]
commit that to the PR :)

**Comment by stdavis** [comment]
I was just kidding. I'm not worried about it.

**Comment by steveoh** [comment]
It's saying it can't find the `MAINTAINERS` i wonder if it needs a txt extension or something.

**Comment by stdavis** [comment]
Or maybe it needs to already be committed to master?

**Comment by steveoh** [comment]
looks like a [master thing](https://github.com/sindresorhus/ava/blob/master/MAINTAINERS).

**Pull request merged**
